---

kind: pipeline
name: moop-ui-ci

steps:
# build node application
# - name: build-ui
#   image: node:8
#   commands:
#   - npm install
#   - npm run build
#   # when:
#   #   event:
#   #   - tag
#   # trigger step when branch release branch push
#   # when:
#   #   branch:
#   #   - dev

- name: rsync-to-web-server
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
  settings:
    hosts:
      - 192.168.0.31
    source: ./build/*
    target: /opt/ui-root

- name: rsync-to-mooplab-web-server
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key_mooplab
    RSYNC_USER:
      from_secret: rsync_user_mooplab
  settings:
    hosts:
      - www.mooplab.com
    source: ./build/*
    target: /opt/ui-root

- name: rsync-to-sctel-web-server
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key_sctel
    RSYNC_USER:
      from_secret: rsync_user_sctel
  settings:
    hosts:
      - sctel.mooplab.com
    source: ./build/*
    target: /storage/moop/ui-root

trigger:
  branch:
  - dev
  # event:
  # - push